# Generated by Django 3.1.7 on 2021-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('hole_1', models.TextField()),
                ('hole_2', models.TextField()),
                ('hole_3', models.TextField()),
                ('hole_4', models.TextField()),
                ('hole_5', models.TextField()),
                ('hole_6', models.TextField()),
                ('hole_7', models.TextField()),
                ('hole_8', models.TextField()),
                ('hole_9', models.TextField()),
                ('hole_10', models.TextField()),
                ('hole_11', models.TextField()),
                ('hole_12', models.TextField()),
                ('hole_13', models.TextField()),
                ('hole_14', models.TextField()),
                ('hole_15', models.TextField()),
                ('hole_16', models.TextField()),
                ('hole_17', models.TextField()),
                ('hole_18', models.TextField()),
            ],
        ),
    ]
