# Generated by Django 3.1.7 on 2021-04-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Scores_Out',
        ),
    ]
