# Generated by Django 3.1.7 on 2021-04-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20210410_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores_out',
            old_name='title',
            new_name='course_played',
        ),
    ]
