# Generated by Django 3.1.7 on 2021-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20210410_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Par_1', models.IntegerField()),
                ('Par_2', models.IntegerField()),
                ('Par_3', models.IntegerField()),
                ('Par_4', models.IntegerField()),
                ('Par_5', models.IntegerField()),
                ('Par_6', models.IntegerField()),
                ('Par_7', models.IntegerField()),
                ('Par_8', models.IntegerField()),
                ('Par_9', models.IntegerField()),
                ('Par_10', models.IntegerField()),
                ('Par_11', models.IntegerField()),
                ('Par_12', models.IntegerField()),
                ('Par_13', models.IntegerField()),
                ('Par_14', models.IntegerField()),
                ('Par_15', models.IntegerField()),
                ('Par_16', models.IntegerField()),
                ('Par_17', models.IntegerField()),
                ('Par_18', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_14',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_16',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_17',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_18',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_9',
            field=models.IntegerField(),
        ),
    ]
