# Generated by Django 3.1.7 on 2021-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20210410_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Blarney', max_length=50),
        ),
    ]
