# Generated by Django 3.1.7 on 2021-04-10 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Par_1',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_10',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_11',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_12',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_13',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_14',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_15',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_16',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_17',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_18',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_2',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_4',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_5',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_6',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_7',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_8',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='Par_9',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
    ]
