# Generated by Django 3.1.7 on 2021-04-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20210410_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_model',
        ),
    ]
