# Generated by Django 3.1.7 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20210416_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
    ]
