# Generated by Django 3.1.7 on 2021-04-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_auto_20210416_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_model',
            old_name='course_name',
            new_name='course_played',
        ),
    ]
