# Generated by Django 3.1.7 on 2021-04-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_course_model_course_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_model',
            name='Course_Par',
        ),
    ]
