# Generated by Django 3.1.7 on 2021-05-03 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_auto_20210501_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='Par_1',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_10',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_11',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_12',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_13',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_14',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_15',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_16',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_17',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_18',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_2',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_4',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_5',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_6',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_7',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_8',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_model',
            name='Par_9',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
