# Generated by Django 3.1.7 on 2021-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_auto_20210516_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
