# Generated by Django 3.1.7 on 2021-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0022_auto_20210516_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='pub_date',
            field=models.TextField(),
        ),
    ]
