# Generated by Django 3.1.7 on 2021-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0023_auto_20210819_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='pub_date',
            field=models.CharField(max_length=50),
        ),
    ]
