# Generated by Django 3.1.7 on 2021-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0024_auto_20210819_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores_out',
            name='tees',
            field=models.CharField(default='Blarney', max_length=10),
        ),
    ]
