# Generated by Django 3.1.7 on 2021-08-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0025_scores_out_tees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='tees',
            field=models.CharField(max_length=10),
        ),
    ]
