# Generated by Django 3.1.7 on 2021-08-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0026_auto_20210819_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores_out',
            old_name='tees',
            new_name='tee',
        ),
    ]
