# Generated by Django 3.1.7 on 2021-10-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0027_auto_20210819_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Lesson', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='long_game_practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_practice', models.DateField()),
                ('number_of_balls', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='short_game_practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.IntegerField()),
            ],
        ),
    ]
