# Generated by Django 3.1.7 on 2021-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0028_date_lesson_long_game_practice_short_game_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores_out',
            name='tee',
        ),
        migrations.AddField(
            model_name='scores_out',
            name='tess',
            field=models.CharField(choices=[('Whites', 'Whites'), ('Blues', 'Blues')], default='Whites', max_length=10),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_1',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_10',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_11',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_12',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_13',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_14',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_15',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_16',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_17',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_18',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_2',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_3',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_4',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_5',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_6',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_7',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_8',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_9',
            field=models.IntegerField(choices=[(1, 'One')]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
