# Generated by Django 3.1.7 on 2021-10-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_auto_20211030_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores_out',
            old_name='tess',
            new_name='tee',
        ),
    ]
