# Generated by Django 3.1.7 on 2021-10-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0030_auto_20211030_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_10',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_11',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_12',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_13',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_14',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_15',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_16',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_17',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_18',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_2',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_3',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_4',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_5',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_6',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_7',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_8',
        ),
        migrations.RemoveField(
            model_name='scores_out',
            name='hole_9',
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_1',
            field=models.CharField(choices=[('1', '1')], max_length=2),
        ),
    ]
