# Generated by Django 3.1.7 on 2021-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0034_auto_20211030_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='tee',
            field=models.CharField(choices=[('Whites', 'Whites'), ('Blues', 'Blues')], default='Whites', max_length=15),
        ),
    ]
