# Generated by Django 3.1.7 on 2021-10-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0035_auto_20211030_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.CharField(choices=[('BLARNEY', 'BLARNEY'), ('MONSTOWN', 'MONSTOWN')], default='BLARNEY', max_length=50),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='tee',
            field=models.CharField(choices=[('Whites', 'Whites'), ('Blues', 'Blues')], default='Whites', max_length=50),
        ),
    ]
