# Generated by Django 3.1.7 on 2021-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0038_auto_20211030_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.CharField(choices=[('Blarney', 'Blarney'), ('Monkstown', 'Monkstown')], default='Blarney', max_length=20),
        ),
    ]
