# Generated by Django 3.1.7 on 2021-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0039_auto_20211030_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores_out',
            options={'ordering': ['pub_date']},
        ),
    ]
