# Generated by Django 3.1.7 on 2021-10-31 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0041_auto_20211031_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='hole_10',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_11',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_12',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_13',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_14',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_15',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_16',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_17',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_18',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_6',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_7',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_8',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_9',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
