# Generated by Django 3.1.7 on 2021-10-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0042_auto_20211031_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='tee',
            field=models.CharField(choices=[('Whites', 'Whites'), ('Blues', 'Blues')], default='Whites', max_length=10),
        ),
    ]
