# Generated by Django 3.1.7 on 2021-11-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0043_course_model_tee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.ForeignKey(default='Blarney', on_delete=django.db.models.deletion.CASCADE, to='scores.course_model'),
        ),
    ]
