# Generated by Django 3.1.7 on 2021-11-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0044_auto_20211103_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.course_model'),
        ),
    ]
