# Generated by Django 3.1.7 on 2021-11-28 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0046_auto_20211105_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores_out',
            name='fairway',
            field=models.CharField(choices=[('Blarney', 'Blarney'), ('Monkstown', 'Monkstown')], default='Hit', max_length=20),
        ),
        migrations.AddField(
            model_name='scores_out',
            name='green',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_1',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 1'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_10',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 10'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_11',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 11'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_12',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 12'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_13',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 13'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_14',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 14'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_15',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 15'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_16',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 16'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_17',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 17'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_18',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 18'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_2',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 2'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 3'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_4',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 4'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_5',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 5'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_6',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 6'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_7',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 7'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_8',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 8'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='hole_9',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hole 9'),
        ),
    ]
