# Generated by Django 3.1.7 on 2021-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0047_auto_20211128_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_out',
            name='fairway',
            field=models.CharField(choices=[('Hit', 'Hit'), ('Left', 'Left'), ('Right', 'Right')], default='Hit', max_length=20),
        ),
    ]
