# Generated by Django 3.1.7 on 2021-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0048_auto_20211128_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores_out',
            name='bunker_up_and_down',
            field=models.BooleanField(default=True, verbose_name=' Bunker Up and Down'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scores_out',
            name='putts',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default='2', max_length=20, verbose_name='No. Of Putts'),
        ),
        migrations.AddField(
            model_name='scores_out',
            name='up_and_down',
            field=models.BooleanField(default=True, verbose_name='Up and Down'),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='green',
            field=models.BooleanField(default=True, verbose_name='Green Hit'),
        ),
    ]
