# Generated by Django 3.1.7 on 2021-11-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0050_auto_20211128_1736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course_model',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='scores_out',
            table='Scores',
        ),
    ]
