# Generated by Django 3.1.7 on 2021-11-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0051_auto_20211128_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='course_played',
            field=models.CharField(default='Blarney', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scores_out',
            name='course_played',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.course_model', to_field='course_played'),
        ),
    ]
