# Generated by Django 3.1.7 on 2021-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0052_auto_20211128_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='course_played',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
