# Generated by Django 3.1.7 on 2021-11-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0053_auto_20211128_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='date',
        ),
        migrations.RemoveField(
            model_name='course_model',
            name='tee',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
